sys-kernel/bootengine: Use update key for initrd sysext download
flatcar/scripts pull request #1160
Opened 2023-09-21 12:00 UTC by pothos

This pulls in https://github.com/flatcar/bootengine/pull/71 to switch the extension download to use the update server and the update key for verification of the payloads.

## How to use

## Testing done

See linked PR

2023-09-21 14:23 UTC, krnowak approved these changes

2023-09-21 14:25 UTC, krnowak requested changes
Uh, actually. Could you also bump the revision of the ebuild to r20?

2023-09-21 15:30 UTC, pothos commented
Yes, done

2023-09-22 10:16 UTC, krnowak approved these changes

2023-09-22 10:17 UTC, merged