sys-kernel/bootengine: Bump to fix slow PXE/ISO boots with udev rule
flatcar/scripts pull request #2249
Opened 2024-08-22 11:05 UTC by chewi

# sys-kernel/bootengine: Bump to fix slow boots with udev rule

See flatcar/bootengine#98 for the details.

Closes: https://github.com/flatcar/Flatcar/issues/1514

## How to use

See flatcar/bootengine#98.

## Testing done

Lots of manual testing and a packages_all_arches Jenkins job, as mentioned in the other PR. I'll do a GitHub run for this PR.

- [X] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [X] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

2024-08-22 11:52 UTC, jepio commented on sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
> +	EGIT_COMMIT="5d4e7312cadaa428af4bc9b32de07e96720656be" # flatcar-master
needs to be d2e22122e8e106a21f64c048992290edc7053384

2024-08-22 11:56 UTC, jepio requested changes
tip: I usually avoid using `Closes:` tags in commit messages, and prefer cross-referencing with `See:`. The issue has now been closed even though we haven't merged the scripts PR yet. Even after this PR is merged, we'd still need to backport to stable-3975 (because that's where the issue was spotted) before we can consider the issue closed. Sometimes it even makes sense to wait until a release has been done.

2024-08-22 12:40 UTC, krnowak approved these changes
If this needs backporting to other channels, make sure you don't backport additional changes in bootengine by accident. If other channels were using different commit for bootengine, we will need to create backport branches in baselayout that contain your fix only.

2024-08-22 15:49 UTC, merged

2024-09-05 15:45 UTC, chewi commented
Oh, sorry about that. Still getting my head around this. I thought alpha just tracked main.