pkg-auto: Add package automation scripts
flatcar/scripts pull request #2342
Opened 2024-09-27 14:34 UTC by krnowak

This adds some scripts I have been using for over a year to deal with the weekly package updates.

It comes with a `README.md` which describes a workflow similar to my own.

The `sync_packages.sh` and `update_packages.sh` scripts are currently not used anywhere. The idea behind them was to use them for Github Action, but that will come as a follow-up PR.

2024-11-29 14:30 UTC, chewi requested changes
I haven't gone over this in detail as you've already walked us through it, and it's already proven itself over months. Your Bash code is also some of the best I've seen. Just need to fix the README and I think you're good to go.

2024-11-29 14:30 UTC, chewi commented on pkg_auto/impl/util.sh
> +}
I guessed you must have done this before I saw the function. "Oh you didn't... oh you did." :rofl: It's fine. :grin:

2024-12-03 14:07 UTC, krnowak commented
Dropped some lines from README and added a paragraph about security fixes at the end of the `Processing the updates (the manual part)` part.

2024-12-03 14:08 UTC, chewi approved these changes

2024-12-03 14:37 UTC, merged