(wip) Automate updates of system packages: sys-apps/*
flatcar/scripts pull request #822
Opened 2023-05-16 06:22 UTC by sayanchowdhury

# Automate updates of system packages: sys-apps/*

Please don't review as this is still a work in progress PR.

TODO
- [ ] Drop the sys-apps/acl as it's already updated.

## Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

- [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

2023-05-22 14:54 UTC, krnowak commented
> * sys-apps/kmod (PROD) (DEV)
>   
>   * from 29 to 39

to 30. But you got it right in the changelog.

> * sys-apps/man-pages (PROD) (DEV)

Is this really in production images? I think it's only dev container.

> * sys-apps/nvme-cli (PROD) (DEV)
>   
>   * from 1.16 to 2.3

This needs some keywords stuff for amd64, because it has version 2.2.1, not 2.3. arm64 has 2.3 (from what I've seen in the build logs).

I couldn't find the package listings for your CI build on bincache, so I can't verify if the versions listed here are actually what's built.

2023-05-22 14:54 UTC, krnowak requested changes

2023-05-22 17:32 UTC, sayanchowdhury commented
> > * sys-apps/kmod (PROD) (DEV)
> >   
> >   * from 29 to 39

Oops! yes. My finger fell a key short :)
> 
> to 30. But you got it right in the changelog.
> 
> > * sys-apps/man-pages (PROD) (DEV)
> 
> Is this really in production images? I think it's only dev container.
> 
> > * sys-apps/nvme-cli (PROD) (DEV)
> >   
> >   * from 1.16 to 2.3
> 
> This needs some keywords stuff for amd64, because it has version 2.2.1, not 2.3. arm64 has 2.3 (from what I've seen in the build logs).
> 
> I couldn't find the package listings for your CI build on bincache, so I can't verify if the versions listed here are actually what's built.

I'll look into both the items tomorrow.

2023-05-25 06:26 UTC, sayanchowdhury commented
I've started another build with the changes: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/821/cldsv/

2023-05-25 12:31 UTC, krnowak commented on changelog/updates/2023-05-04-package-updates-sys-apps.md
> +- debianutils ([5.7](https://metadata.ftp-master.debian.org/changelogs//main/d/debianutils/debianutils_5.7-0.4_changelog))
I'd drop it, it's not a part of developer container nor production image, and probably not that important part of SDK anyway.

2023-05-25 14:19 UTC, krnowak commented
> I don't know why nvme-cli started installing udev and systemd stuff in parent directories (and I don't know if that's a problem):
> 
> ```diff
> +/usr/lib/udev/70-nvmf-autoconnect.rules
> +/usr/lib/udev/71-nvmf-iopolicy-netapp.rules
> -/usr/lib/udev/rules.d/70-nvmf-autoconnect.rules
> -/usr/lib/udev/rules.d/71-nvmf-iopolicy-netapp.rules
> +/usr/lib/systemd/nvmefc-boot-connections.service
> +/usr/lib/systemd/nvmf-autoconnect.service
> +/usr/lib/systemd/nvmf-connect.target
> +/usr/lib/systemd/nvmf-connect@.service
> -/usr/lib/systemd/system/nvmefc-boot-connections.service
> -/usr/lib/systemd/system/nvmf-autoconnect.service
> -/usr/lib/systemd/system/nvmf-connect.target
> -/usr/lib/systemd/system/nvmf-connect@.service
> ```

I'm going to file a PR in gentoo to fix these.

2023-05-25 15:05 UTC, krnowak commented
Needs a rebase.

2023-05-26 04:45 UTC, krnowak commented
Gentoo PR is merged, so maybe you could sync sys-apps/nvme-cli and sys-libs/libnvme again with gentoo and add keywords to pick up nvme-cli-2.4-r2.ebuild and libnvme-1.4 for both amd64 and arm64? This should fix the installation location of the files.

2023-06-05 12:11 UTC, sayanchowdhury commented
Rebase and CI running: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/837/cldsv/

2023-06-05 15:13 UTC, krnowak commented on sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
> +=sys-libs/libnvme-1.4 ~amd64 ~arm64
These are not necessary any more - these ebuilds got stabilized on both amd64 and arm64 since I made a comment about these.

2023-06-15 09:11 UTC, merged